kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: php
  namespace: bharaths-php
  selfLink: /apis/apps.openshift.io/v1/namespaces/bharaths-php/deploymentconfigs/php
  uid: 9e8fa82a-8dc1-11e9-9793-0a580a81007e
  resourceVersion: '16208198'
  generation: 1
  creationTimestamp: '2019-06-13T09:57:13Z'
  labels:
    app: php
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - php
        from:
          kind: ImageStreamTag
          namespace: bharaths-php
          name: 'php:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: php
    deploymentconfig: php
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php
        deploymentconfig: php
    spec:
      containers:
        - name: php
          image: 'php:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  latestVersion: 0
  observedGeneration: 1
  replicas: 0
  updatedReplicas: 0
  availableReplicas: 0
  unavailableReplicas: 0
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2019-06-13T09:57:14Z'
      lastTransitionTime: '2019-06-13T09:57:14Z'
      message: Deployment config does not have minimum availability.
